-- ============================================================================
-- DEPRECATED & UNSAFE — DO NOT EXECUTE THIS FILE
-- ============================================================================
-- This prototype schema created generic objects in the public namespace (e.g. public.rooms).
-- It has been archived for historical reference in:
--   supabase/_archive/public-schema-prototype-unsafe.sql
--
-- FOR INSTALLATION IN A SHARED SUPABASE PROJECT, EXECUTE:
--   1. supabase/preflight-team-pulse.sql
--   2. supabase/install-team-pulse.sql
--   3. supabase/verify-team-pulse.sql
-- ============================================================================
